package viewer;


import controller.FuncoesUteis;
import controller.GerInterGrafica;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 1547816
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    // Usado para não redimensionar a imagem de fundo toda hora
    private Timer resizeTimer;
    
    
    public FrmPrincipal() {
        
        // Timer para atrasar a atualização da imagem
        resizeTimer = new Timer(500, e -> {
            FuncoesUteis.mostrarFoto(lblImagem, lblImagem.getIcon() );
            resizeTimer.stop(); // Para o timer após a atualização
        });
        resizeTimer.setRepeats(false);
        
        
        initComponents();
        
         // Carregar o ícone (deve estar na pasta do projeto, dentro de "resources")
         
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/Hamburguer.jpg"));
        this.setIconImage( icon.getImage() );
        
      //  FuncoesUteis.mostrarFoto(lblImagem, lblImagem.getIcon() );
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTeste = new javax.swing.ButtonGroup();
        grupoMenu = new javax.swing.ButtonGroup();
        grpAparencia = new javax.swing.ButtonGroup();
        pnlFundo = new javax.swing.JPanel();
        lblImagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCadCliente = new javax.swing.JMenuItem();
        mnuCadLanche = new javax.swing.JMenuItem();
        mnuCadPedido = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuOpcoes = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mnuWindows = new javax.swing.JRadioButtonMenuItem();
        mnuNimbus = new javax.swing.JRadioButtonMenuItem();
        mnuMetal = new javax.swing.JRadioButtonMenuItem();
        mnuMotif = new javax.swing.JRadioButtonMenuItem();
        mnuLight = new javax.swing.JRadioButtonMenuItem();
        mnuDark = new javax.swing.JRadioButtonMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema XFome vs 1.0");
        setPreferredSize(new java.awt.Dimension(800, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        pnlFundo.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlFundo, java.awt.BorderLayout.CENTER);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Hamburguer.jpg"))); // NOI18N
        lblImagem.setText("jLabel1");
        getContentPane().add(lblImagem, java.awt.BorderLayout.CENTER);

        jMenu1.setMnemonic('C');
        jMenu1.setText("Cadastros");

        mnuCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/user.png"))); // NOI18N
        mnuCadCliente.setText("Cliente");
        mnuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCadCliente);

        mnuCadLanche.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadLanche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/archive.png"))); // NOI18N
        mnuCadLanche.setText("Lanche");
        jMenu1.add(mnuCadLanche);

        mnuCadPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/shopping_cart.png"))); // NOI18N
        mnuCadPedido.setText("Pedido");
        mnuCadPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadPedidoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCadPedido);
        jMenu1.add(jSeparator1);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/remove.png"))); // NOI18N
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('P');
        jMenu2.setText("Pesquisas");

        jMenu5.setText("Cliente");

        jMenuItem5.setText("por Nome");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("por Bairro");
        jMenu5.add(jMenuItem6);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('F');
        jMenu3.setText("Ferramentas");

        mnuOpcoes.setText("Opções");
        mnuOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpcoesActionPerformed(evt);
            }
        });
        jMenu3.add(mnuOpcoes);

        jMenu7.setText("Aparência");

        grpAparencia.add(mnuWindows);
        mnuWindows.setMnemonic('W');
        mnuWindows.setSelected(true);
        mnuWindows.setText("Windows");
        mnuWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWindowsActionPerformed(evt);
            }
        });
        jMenu7.add(mnuWindows);

        grpAparencia.add(mnuNimbus);
        mnuNimbus.setMnemonic('N');
        mnuNimbus.setText("Nimbus");
        mnuNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWindowsActionPerformed(evt);
            }
        });
        jMenu7.add(mnuNimbus);

        grpAparencia.add(mnuMetal);
        mnuMetal.setMnemonic('M');
        mnuMetal.setText("Metal");
        mnuMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWindowsActionPerformed(evt);
            }
        });
        jMenu7.add(mnuMetal);

        grpAparencia.add(mnuMotif);
        mnuMotif.setMnemonic('F');
        mnuMotif.setText("Motif");
        mnuMotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWindowsActionPerformed(evt);
            }
        });
        jMenu7.add(mnuMotif);

        grpAparencia.add(mnuLight);
        mnuLight.setMnemonic('L');
        mnuLight.setText("FlatLaf Light");
        mnuLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWindowsActionPerformed(evt);
            }
        });
        jMenu7.add(mnuLight);

        grpAparencia.add(mnuDark);
        mnuDark.setMnemonic('D');
        mnuDark.setText("FlatLaf Dark");
        mnuDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWindowsActionPerformed(evt);
            }
        });
        jMenu7.add(mnuDark);

        jMenu3.add(jMenu7);

        jMenu6.setText("Radio Menu");

        grupoMenu.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setText("FM");
        jMenu6.add(jRadioButtonMenuItem1);

        grupoMenu.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("AM");
        jMenu6.add(jRadioButtonMenuItem2);

        jMenu3.add(jMenu6);

        jMenu8.setText("Check Menu");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
        jMenu8.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");
        jMenu8.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");
        jMenu8.add(jCheckBoxMenuItem3);

        jMenu3.add(jMenu8);

        jMenuBar1.add(jMenu3);

        jMenu4.setMnemonic('A');
        jMenu4.setText("Ajuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadClienteActionPerformed
        GerInterGrafica.getMyInstance().abrirCadCliente();
    }//GEN-LAST:event_mnuCadClienteActionPerformed

    private void mnuWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuWindowsActionPerformed
        trocarLookAndFeel( grpAparencia.getSelection().getMnemonic()  );
    }//GEN-LAST:event_mnuWindowsActionPerformed

    private void mnuCadPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadPedidoActionPerformed
        GerInterGrafica.getMyInstance().abrirCadPedido();  
    }//GEN-LAST:event_mnuCadPedidoActionPerformed

    private void mnuOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpcoesActionPerformed
        GerInterGrafica.getMyInstance().abrirFerramentas();
    }//GEN-LAST:event_mnuOpcoesActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        resizeTimer.restart();
    }//GEN-LAST:event_formComponentResized

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        GerInterGrafica.getMyInstance().sair();
    }//GEN-LAST:event_mnuSairActionPerformed

    // Trocar a aparência durante a execução
    private void trocarLookAndFeel(int nomeLook) {
        
        try {
            String lookAndFeel = switch (nomeLook) {
                case 'N' -> "javax.swing.plaf.nimbus.NimbusLookAndFeel";
                case 'F' -> "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
                case 'W' -> "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";  
                case 'L' -> "com.formdev.flatlaf.FlatLightLaf";
                case 'D' -> "com.formdev.flatlaf.FlatDarkLaf";
                default -> "javax.swing.plaf.metal.MetalLookAndFeel";   // Padrão do Java
            };
            UIManager.setLookAndFeel(lookAndFeel);
            SwingUtilities.updateComponentTreeUI(this);
            pack();     // Ajusta o tamanho da janela para refletir a nova aparência
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar a aparência. " + ex,
                    "Principal", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grpAparencia;
    private javax.swing.ButtonGroup grupoMenu;
    private javax.swing.ButtonGroup grupoTeste;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JMenuItem mnuCadCliente;
    private javax.swing.JMenuItem mnuCadLanche;
    private javax.swing.JMenuItem mnuCadPedido;
    private javax.swing.JRadioButtonMenuItem mnuDark;
    private javax.swing.JRadioButtonMenuItem mnuLight;
    private javax.swing.JRadioButtonMenuItem mnuMetal;
    private javax.swing.JRadioButtonMenuItem mnuMotif;
    private javax.swing.JRadioButtonMenuItem mnuNimbus;
    private javax.swing.JMenuItem mnuOpcoes;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JRadioButtonMenuItem mnuWindows;
    private javax.swing.JPanel pnlFundo;
    // End of variables declaration//GEN-END:variables
}

