/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.viewer;

import com.controller.graficinterface.GenericTableModel;
import com.domain.Fazenda;
import com.viewer.CadastrarBovino;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class GerenciarFazenda extends javax.swing.JFrame {

    private int contadorID = 1; // Variável para gerar IDs únicos
    private int linhaEditando = -1; // Armazena o índice da linha que está sendo editada
    private GenericTableModel<Fazenda> tableModel;
    
    public GerenciarFazenda() {
        initComponents();
        adicionarListenerSpinner();
        
         // Definir as colunas e os atributos da tabela
        String[] colunas = {"ID", "Nome da Fazenda", "Localizacao", "Tamanho (ha)", "Qtde. Bovinos", "Observações"};
        String[] atributos = {"","","","","",""}; //Iguais aos campos do objeto

        // Criar o modelo genérico e associar à JTable
        tableModel = new GenericTableModel<>(colunas, atributos);
        tabelaFazendas.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFazenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        formatedLocalizacaoFazenda = new javax.swing.JFormattedTextField();
        spinnerQtdBovinos = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spinnerTamanhoHectares = new javax.swing.JSpinner();
        lblQtdBovinos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoesFazenda = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaFazendas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblTotalBovinosFazenda = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTamanhoFazenda = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        progressCapacidadeBovinos = new javax.swing.JProgressBar();
        lblPorcentagemCapacidadeBovinos = new javax.swing.JLabel();
        lblRacaMaisComum = new javax.swing.JLabel();
        lbltoTotalBovino = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRetornar = new javax.swing.JMenu();
        menuVoltarHome = new javax.swing.JMenuItem();
        menuGerenciaGado = new javax.swing.JMenu();
        menuGerenciarGado = new javax.swing.JMenuItem();
        menuMovimentacoes = new javax.swing.JMenu();
        menuMovimentacao = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro da Fazenda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("URW Gothic", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Localizacao:");

        jLabel2.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Nome da Fazenda :");

        jLabel3.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Tamanho da Fazenda (hectares) :");

        jLabel4.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Observacoes :");

        lblQtdBovinos.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        lblQtdBovinos.setText("0");

        jLabel7.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        jLabel8.setText("Quantidade de Bovinos:");

        txtObservacoesFazenda.setColumns(20);
        txtObservacoesFazenda.setRows(5);
        jScrollPane1.setViewportView(txtObservacoesFazenda);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formatedLocalizacaoFazenda)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(spinnerTamanhoHectares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spinnerQtdBovinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(lblQtdBovinos)))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel7)
                    .addContainerGap(1354, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(formatedLocalizacaoFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(spinnerTamanhoHectares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81)
                .addComponent(jLabel4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerQtdBovinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdBovinos)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(jLabel7)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botoes de Acao", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("URW Gothic", 1, 18))); // NOI18N

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(btnInserir))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Fazendas Registradas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("URW Gothic", 1, 18))); // NOI18N

        tabelaFazendas.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        tabelaFazendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome da Fazenda", "Localizacao", "Tamanho (ha)", "Qtd. Bovinos", "Observacoes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaFazendas.setDoubleBuffered(true);
        tabelaFazendas.setRowHeight(50);
        tabelaFazendas.setRowMargin(10);
        tabelaFazendas.setShowGrid(true);
        jScrollPane2.setViewportView(tabelaFazendas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1343, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estatasticas Resumidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("URW Gothic", 1, 18))); // NOI18N

        lblTotalBovinosFazenda.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        lblTotalBovinosFazenda.setText("0");

        jLabel10.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel10.setText("Capacidade de Bovinos:");

        jLabel11.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel11.setText("Total de Fazendas:");

        jLabel12.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N

        lblTamanhoFazenda.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        lblTamanhoFazenda.setText("750 hectares ");

        jLabel14.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel14.setText("Media de Tamanho:");

        jLabel15.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel15.setText("Total de Bovinos:");

        jLabel16.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel16.setText("Raca Mais Comum:");

        progressCapacidadeBovinos.setForeground(new java.awt.Color(51, 255, 0));
        progressCapacidadeBovinos.setValue(10);

        lblPorcentagemCapacidadeBovinos.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        lblPorcentagemCapacidadeBovinos.setText("10%");

        lblRacaMaisComum.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        lblRacaMaisComum.setText(" Nelore");

        lbltoTotalBovino.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        lbltoTotalBovino.setText("320");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(40, 40, 40)
                                .addComponent(lblRacaMaisComum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(53, 53, 53)
                                .addComponent(lbltoTotalBovino, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(progressCapacidadeBovinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(lblPorcentagemCapacidadeBovinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTamanhoFazenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalBovinosFazenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalBovinosFazenda)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblTamanhoFazenda)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lbltoTotalBovino))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblRacaMaisComum))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressCapacidadeBovinos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentagemCapacidadeBovinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuRetornar.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/FarmFormII/src/resorces/imagens/home.png")); // NOI18N
        menuRetornar.setText("Home");

        menuVoltarHome.setText("Voltar");
        menuVoltarHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVoltarHomeActionPerformed(evt);
            }
        });
        menuRetornar.add(menuVoltarHome);

        jMenuBar1.add(menuRetornar);

        menuGerenciaGado.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/FarmFormII/src/resorces/boi_16x16.png")); // NOI18N
        menuGerenciaGado.setText("Gado");

        menuGerenciarGado.setText("Gerenciamento de Gado");
        menuGerenciarGado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarGadoActionPerformed(evt);
            }
        });
        menuGerenciaGado.add(menuGerenciarGado);

        jMenuBar1.add(menuGerenciaGado);

        menuMovimentacoes.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/FarmFormII/src/resorces/16x16/3d bar chart.png")); // NOI18N
        menuMovimentacoes.setText("Movimentacoes");

        menuMovimentacao.setText("Movimentacoes");
        menuMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMovimentacaoActionPerformed(evt);
            }
        });
        menuMovimentacoes.add(menuMovimentacao);

        jMenuBar1.add(menuMovimentacoes);

        jMenu5.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/FarmFormII/src/resorces/imagens/note_edit.png")); // NOI18N
        jMenu5.setText("Relatorio");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGerenciarGadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarGadoActionPerformed
        // Criando e exibindo a tela de Cadastro de Bovinos
        System.out.println("Abrindo tela de Gerenciamento de Gado...");
        CadastrarBovino bovinoFrame = new CadastrarBovino();
        bovinoFrame.setVisible(true);

        // Ocultando a tela atual (Home)
        this.dispose();
    }//GEN-LAST:event_menuGerenciarGadoActionPerformed

    private void menuMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMovimentacaoActionPerformed
        // Criando e exibindo a tela de Movimentações
        Movimentacao movimentacaoFrame = new Movimentacao();
        movimentacaoFrame.setVisible(true);

        // Ocultando a tela atual (Home)
        this.dispose();
    }//GEN-LAST:event_menuMovimentacaoActionPerformed

    private void menuVoltarHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVoltarHomeActionPerformed
        // Criando e exibindo a Home novamente
        Home homeFrame = new Home();
        homeFrame.setVisible(true);

        // Fechando a tela atual
        this.dispose();
    }//GEN-LAST:event_menuVoltarHomeActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        inserirFazenda();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluirFazenda();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        carregarDadosParaCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvarAlteracoes();
    }//GEN-LAST:event_btnSalvarActionPerformed

    // Método para adicionar um listener ao JSpinner
    private void adicionarListenerSpinner() {
        spinnerQtdBovinos.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                atualizarLabelQtdBovinos();
            }
        });
    }

    // Método que atualiza a label conforme o usuário altera o spinner
    private void atualizarLabelQtdBovinos() {
        int qtdBovinos = (int) spinnerQtdBovinos.getValue();
        lblQtdBovinos.setText(String.valueOf(qtdBovinos)); // Atualiza a label
    }
    
    // Método principal chamado ao clicar no botão "Inserir"
    private void inserirFazenda() {
        String[] dados = obterDadosFormulario();
        
        if (!validarCampos(dados)) {
            return; // Se a validação falhar, sai da função
        }

        int[] valoresNumericos = converterValores(dados[2], dados[3]);
        if (valoresNumericos == null) {
            return; // Se a conversão falhar, sai da função
        }

        adicionarNaTabela(contadorID++, dados[0], dados[1], valoresNumericos[0], valoresNumericos[1], dados[4]);
        limparCampos();
        mostrarMensagem("Fazenda adicionada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }

    // Obtém os dados digitados nos campos e retorna como um array de Strings
    private String[] obterDadosFormulario() {
        return new String[]{
            txtNomeFazenda.getText().trim(),
            formatedLocalizacaoFazenda.getText().trim(),
            spinnerTamanhoHectares.getValue().toString(), // Obtém o valor do JSpinner
            spinnerQtdBovinos.getValue().toString(), // Obtém o valor do JSpinner
            txtObservacoesFazenda.getText().trim()
        };
    }

    // Valida se os campos obrigatórios foram preenchidos
    private boolean validarCampos(String[] dados) {
        if (dados[0].isEmpty() || dados[1].isEmpty() || dados[2].isEmpty() || dados[3].isEmpty()) {
            mostrarMensagem("Preencha todos os campos obrigatórios!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    // Converte os valores numéricos e retorna um array com os valores convertidos
    private int[] converterValores(String tamanhoStr, String qtdBovinosStr) {
        try {
            int tamanho = Integer.parseInt(tamanhoStr); // Garante que o tamanho seja um número inteiro
            int qtdBovinos = Integer.parseInt(qtdBovinosStr);
            return new int[]{tamanho, qtdBovinos};
        } catch (NumberFormatException e) {
            mostrarMensagem("Os campos 'Tamanho da Fazenda' e 'Quantidade de Bovinos' devem ser números inteiros!", "Erro", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    // Adiciona os dados na tabela com um ID gerado automaticamente
    private void adicionarNaTabela(int id, String nome, String localizacao, int tamanho, int qtdBovinos, String observacoes) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaFazendas.getModel();
        modelo.addRow(new Object[]{id, nome, localizacao, tamanho, qtdBovinos, observacoes});
    }

    // Exibe mensagens para o usuário
    private void mostrarMensagem(String mensagem, String titulo, int tipo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, tipo);
    }

    // Método para limpar os campos após a inserção
    private void limparCampos() {
        txtNomeFazenda.setText("");
        formatedLocalizacaoFazenda.setValue(null);
        spinnerTamanhoHectares.setValue(0);
        spinnerQtdBovinos.setValue(0);
        txtObservacoesFazenda.setText("");
        txtNomeFazenda.requestFocus();
    }
    
    // Método principal para excluir a fazenda selecionada
    private void excluirFazenda() {
        int linhaSelecionada = tabelaFazendas.getSelectedRow();

        if (linhaSelecionada == -1) {
            mostrarMensagem("Selecione uma fazenda para excluir!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirmação antes da exclusão
        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir esta fazenda?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.NO_OPTION) {
            return;
        }

        // Obtém o modelo da tabela e remove a linha selecionada
        DefaultTableModel modelo = (DefaultTableModel) tabelaFazendas.getModel();
        modelo.removeRow(linhaSelecionada);

        mostrarMensagem("Fazenda excluída com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void carregarDadosParaCampos() {
        int linhaSelecionada = tabelaFazendas.getSelectedRow();

        if (linhaSelecionada == -1) {
            mostrarMensagem("Selecione uma fazenda para alterar!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtendo o modelo da tabela e os valores da linha selecionada
        DefaultTableModel modelo = (DefaultTableModel) tabelaFazendas.getModel();

        int id = (int) modelo.getValueAt(linhaSelecionada, 0); // ID da fazenda
        String nome = (String) modelo.getValueAt(linhaSelecionada, 1);
        String localizacao = (String) modelo.getValueAt(linhaSelecionada, 2);
        int tamanho = (int) modelo.getValueAt(linhaSelecionada, 3);
        int qtdBovinos = (int) modelo.getValueAt(linhaSelecionada, 4);
        String observacoes = (String) modelo.getValueAt(linhaSelecionada, 5);

        // Preenchendo os campos de entrada com os valores da tabela
        txtNomeFazenda.setText(nome);
        formatedLocalizacaoFazenda.setText(localizacao);
        spinnerTamanhoHectares.setValue(tamanho);
        spinnerQtdBovinos.setValue(qtdBovinos);
        txtObservacoesFazenda.setText(observacoes);

        // Armazenamos a linha selecionada para futura atualização
        this.linhaEditando = linhaSelecionada;
    }
    
    private void salvarAlteracoes() {
        if (linhaEditando == -1) {
            mostrarMensagem("Nenhuma edição em andamento!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] dados = obterDadosFormulario();

        if (!validarCampos(dados)) {
            return;
        }

        int[] valoresNumericos = converterValores(dados[2], dados[3]);
        if (valoresNumericos == null) {
            return;
        }

        // Obtendo o modelo da tabela e atualizando os dados na linha selecionada
        DefaultTableModel modelo = (DefaultTableModel) tabelaFazendas.getModel();

        modelo.setValueAt(dados[0], linhaEditando, 1); // Nome
        modelo.setValueAt(dados[1], linhaEditando, 2); // Localização
        modelo.setValueAt(valoresNumericos[0], linhaEditando, 3); // Tamanho (ha)
        modelo.setValueAt(valoresNumericos[1], linhaEditando, 4); // Quantidade de Bovinos
        modelo.setValueAt(dados[4], linhaEditando, 5); // Observações

        // Resetamos a variável de edição e limpamos os campos
        linhaEditando = -1;
        limparCampos();
        mostrarMensagem("Alteração realizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarFazenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarFazenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarFazenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarFazenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerenciarFazenda dialog = new GerenciarFazenda();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JFormattedTextField formatedLocalizacaoFazenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPorcentagemCapacidadeBovinos;
    private javax.swing.JLabel lblQtdBovinos;
    private javax.swing.JLabel lblRacaMaisComum;
    private javax.swing.JLabel lblTamanhoFazenda;
    private javax.swing.JLabel lblTotalBovinosFazenda;
    private javax.swing.JLabel lbltoTotalBovino;
    private javax.swing.JMenu menuGerenciaGado;
    private javax.swing.JMenuItem menuGerenciarGado;
    private javax.swing.JMenuItem menuMovimentacao;
    private javax.swing.JMenu menuMovimentacoes;
    private javax.swing.JMenu menuRetornar;
    private javax.swing.JMenuItem menuVoltarHome;
    private javax.swing.JProgressBar progressCapacidadeBovinos;
    private javax.swing.JSpinner spinnerQtdBovinos;
    private javax.swing.JSpinner spinnerTamanhoHectares;
    private javax.swing.JTable tabelaFazendas;
    private javax.swing.JTextField txtNomeFazenda;
    private javax.swing.JTextArea txtObservacoesFazenda;
    // End of variables declaration//GEN-END:variables
}
