/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view.windows;

import com.view.windows.CadastrarBovino;

/**
 *
 * @author lucas
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGerenciaFazenda = new javax.swing.JMenu();
        menuGerenciarFazendas = new javax.swing.JMenuItem();
        menuGerenciaGado = new javax.swing.JMenu();
        menuGerenciarGado = new javax.swing.JMenuItem();
        menuMovimentacoes = new javax.swing.JMenu();
        menuMovimentacao = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Te X Gyre Bonum", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem Vindo ao FarmForm!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/lucas/Documentos/ifes-3ano/SI-IFES-III/poo2/trabDev/FarmForm/src/imagens/IMAGEM IA - PECUARISTA TRABALHANDO NO CAMPO EM CIMA DE UM CAVALO TOCANDO O GADO AO AMANHECER (6).png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        menuGerenciaFazenda.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/FarmFormII/src/resorces/fazenda_16x16.png")); // NOI18N
        menuGerenciaFazenda.setText("Fazenda");

        menuGerenciarFazendas.setText("Gerenciar Fazendas");
        menuGerenciarFazendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarFazendasActionPerformed(evt);
            }
        });
        menuGerenciaFazenda.add(menuGerenciarFazendas);

        jMenuBar1.add(menuGerenciaFazenda);

        menuGerenciaGado.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/FarmFormII/src/resorces/boi_16x16.png")); // NOI18N
        menuGerenciaGado.setText("Gado");

        menuGerenciarGado.setText("Gerenciamento de Gado");
        menuGerenciarGado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarGadoActionPerformed(evt);
            }
        });
        menuGerenciaGado.add(menuGerenciarGado);

        jMenuBar1.add(menuGerenciaGado);

        menuMovimentacoes.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/FarmFormII/src/resorces/16x16/3d bar chart.png")); // NOI18N
        menuMovimentacoes.setText("Movimentacoes");

        menuMovimentacao.setText("Movimentacoes");
        menuMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMovimentacaoActionPerformed(evt);
            }
        });
        menuMovimentacoes.add(menuMovimentacao);

        jMenuBar1.add(menuMovimentacoes);

        jMenu5.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/FarmFormII/src/resorces/imagens/note_edit.png")); // NOI18N
        jMenu5.setText("Relatorio");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGerenciarFazendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarFazendasActionPerformed
        // Criando e exibindo a tela de Gerenciamento da Fazenda
        GerenciarFazenda fazendaFrame = new GerenciarFazenda();
        fazendaFrame.setVisible(true);

        // Ocultando a tela atual (Home)
        this.dispose();
    }//GEN-LAST:event_menuGerenciarFazendasActionPerformed

    private void menuGerenciarGadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarGadoActionPerformed
        // Criando e exibindo a tela de Cadastro de Bovinos
        
        CadastrarBovino bovinoFrame = new CadastrarBovino();
        bovinoFrame.setVisible(true);

        // Ocultando a tela atual (Home)
        this.dispose();
    }//GEN-LAST:event_menuGerenciarGadoActionPerformed

    private void menuMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMovimentacaoActionPerformed
        // Criando e exibindo a tela de Movimentações
        Movimentacao movimentacaoFrame = new Movimentacao();
        movimentacaoFrame.setVisible(true);

        // Ocultando a tela atual (Home)
        this.dispose();
    }//GEN-LAST:event_menuMovimentacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuGerenciaFazenda;
    private javax.swing.JMenu menuGerenciaGado;
    private javax.swing.JMenuItem menuGerenciarFazendas;
    private javax.swing.JMenuItem menuGerenciarGado;
    private javax.swing.JMenuItem menuMovimentacao;
    private javax.swing.JMenu menuMovimentacoes;
    // End of variables declaration//GEN-END:variables
}
