// src/config/modules.js

import { atoresArray } from "../../assets/database/atores";
import { classesArray } from "../../assets/database/classes";
import { diretoresArray } from "../../assets/database/diretores";
import { titulosArray } from "../../assets/database/titulos";
import { itensArray } from "../../assets/database/itens";
import { filtrarCampos } from "../utils";
export const excludeFields = [
  "id",
  "ativo",
  "data_nascimento",
  "nacionalidade",
  "Nacionalidade",
  "classeId",
  "classeId",
  "diretorId",
  "tituloId",
  "atoresIds"
];

// auto form maker usa databaseSchema para criar os formularios
// [] vetores informa que o sistema deve criar um select
// preencher depois da chave:valor informa que o sistema deve preencher automaticamente o input
// ex: nome: "arnold"

// backendPayloadMinimalRequired e o que o servidor espera receber de payload
// databaseSchema e o que o servidor envia de dados
// generated by /swagger-ui/index.html

// moduleConfig
const modules = [
  {
    name: "atores",
    label: "Atores",
    description:
      "Este caso de uso é responsável pelo controle de atores, abrangendo a inclusão de um novo ator, alteração e exclusão.",
    data: filtrarCampos(excludeFields, atoresArray),
    databaseSchema: {
      id: 0,
      nome: "Arnold Schwarzenegger",
    },
    backendPayloadMinimalRequired: {
      nome: "string",
    },
  },

  {
    name: "classes",
    label: "Classes",
    description:
      "Este caso de uso é responsável pelo controle de classes, abrangendo a inclusão de uma nova classe, alteração e exclusão.",
    data: filtrarCampos(excludeFields, classesArray),
    databaseSchema: {
      id: 0,
      nome: "string",
      precoDiariaCentavos: 0,
      dataDevolucao: "2025-11-01",
    },
    backendPayloadMinimalRequired: {
      nome: "string",
      precoDiariaCentavos: 0,
      dataDevolucao: "2025-11-01",
    },
  },
  {
    name: "diretores",
    label: "Diretores",
    description:
      "Este caso de uso é responsável pelo controle de diretores, abrangendo a inclusão de um novo ator, alteração e exclusão.",
    data: filtrarCampos(excludeFields, diretoresArray),
    databaseSchema: {
      id: 0,
      nome: "string",
    },
    backendPayloadMinimalRequired: {
      nome: "string",
    },
  },
  {
    name: "itens",
    label: "Itens",
    description:
      "Este caso de uso é responsável pelo controle de itens (fitas ouDVDs), abrangendo a inclusão, alteração, consulta e exclusão de itens.",
    data: filtrarCampos(excludeFields, itensArray),
    databaseSchema: {
      id: 0,
      numSerie: 7415872,
      dtAquisicao: "30-08-1991",
      tipoItem: ["DVD","fita","Blue Ray"],
      titulo: ["Terminator 2"],
    },
    backendPayloadMinimalRequired: {
      numSerie: "string",
      dtAquisicao: "2025-11-01",
      tipoItem: "string",
      tituloId: 0,
    },
  },
  {
    name: "titulos",
    label: "Títulos",
    description:
      "Este caso de uso é responsável pelo controle de títulos, abrangendo ainclusãode um novo título, alteração, consulta e exclusão de títulos existentes.",
    data: filtrarCampos(excludeFields, titulosArray),
    databaseSchema: {
      id: 0,
      nome: "Terminator 2",
      ano: 1991,
      sinopse: "O jovem John Connor é a chave para a vitória da humanidade sobre a rebelião das máquinas no futuro. O garoto é alvo de T-1000, um exterminador feito de metal líquido que pode assumir a forma que desejar e que foi enviado do futuro para matá-lo. Outro exterminador, o renovado T-800, também é mandado de volta para proteger o menino. Enquanto John e sua mãe, Sarah Connor, fogem com o T-800, o garoto cria um vínculo afetivo inesperado com o robô.",
      categoria: "Ficção Científica",
      // classeId: 0,
      classeNome: ["Lançamento"],
      // diretorId: 0,
      diretorNome: ["James Cameron"],
      atoresNomes: [
        "Arnold Schwarzenegger",
        "Linda Hamilton",
        "Edward Furlong",
        "Robert Patrick",
      ],
      // atoresIds: [0],
    },
    backendPayloadMinimalRequired: {
      nome: "string",
      ano: 1900,
      sinopse: "string",
      categoria: "string",
      // id da classe
      classeId: 0,
      // id do diretor
      diretorId: 0,
      // id dos N atores
      atoresIds: [0],
    },
  },
  {
    name: "clientes/socio",
    label: "clientes",
    description:
      "Este caso de uso é responsável pelo controle de títulos, abrangendo ainclusãode um novo título, alteração, consulta e exclusão de títulos existentes.",
    // data: filtrarCampos(excludeFields, titulosArray),
    // databaseSchema:
    backendPayloadMinimalRequired: {
      nome: "string",
      dtNascimento: "2025-11-01",
      sexo: "string",
      cpf: "string",
      endereco: "string",
      telefone: "string",
      dependentes: [
        {
          nome: "string",
          dtNascimento: "2025-11-01",
          sexo: "string",
        },
      ],
    },
  },
];


export default modules;
