// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe89jZAbfSlf5o3rH_V86ViJGLkgWi7cA',
    appId: '1:859442683473:web:0358bfde7073e37c78e270',
    messagingSenderId: '859442683473',
    projectId: 'teste-29485',
    authDomain: 'teste-29485.firebaseapp.com',
    storageBucket: 'teste-29485.firebasestorage.app',
    measurementId: 'G-W9GBPN8T8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLcENMiw9ghy-g2iyghU8WPDlZBnRNNbI',
    appId: '1:859442683473:android:fbc78b939d67283878e270',
    messagingSenderId: '859442683473',
    projectId: 'teste-29485',
    storageBucket: 'teste-29485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4cWRfkGjGODVs7VOvonsTR1yc6wrAh5Y',
    appId: '1:859442683473:ios:a21b3384b0ea776078e270',
    messagingSenderId: '859442683473',
    projectId: 'teste-29485',
    storageBucket: 'teste-29485.firebasestorage.app',
    iosBundleId: 'com.example.mercadim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4cWRfkGjGODVs7VOvonsTR1yc6wrAh5Y',
    appId: '1:859442683473:ios:a21b3384b0ea776078e270',
    messagingSenderId: '859442683473',
    projectId: 'teste-29485',
    storageBucket: 'teste-29485.firebasestorage.app',
    iosBundleId: 'com.example.mercadim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe89jZAbfSlf5o3rH_V86ViJGLkgWi7cA',
    appId: '1:859442683473:web:00df9485f0db66f378e270',
    messagingSenderId: '859442683473',
    projectId: 'teste-29485',
    authDomain: 'teste-29485.firebaseapp.com',
    storageBucket: 'teste-29485.firebasestorage.app',
    measurementId: 'G-JPCQ7KC7FC',
  );
}
